services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
  authorization-server:
    container_name: authorization-server
    build:
      context: .
      dockerfile: authorization-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LISTEN_ADDR=:8080
      - JWT_SIGNING_KEY=some-local-secret
      - DB_CONN_STRING=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  workout-tracker-server:
    container_name: workout-tracker-server
    build:
      context: .
      dockerfile: workout-tracker-server/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - LISTEN_ADDR=:8080
      - JWT_SIGNING_KEY=some-local-secret
      - DB_CONN_STRING=postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres