= workout-tracker

Workout tracker REST < - > gRPC implementation based on project idea - https://roadmap.sh/projects/fitness-workout-tracker

:toc:

== Architecture

== Stack & Tools

- grpc-gateway as reverse proxy to expose gRPC services as REST
* project link https://github.com/grpc-ecosystem/grpc-gateway
* grpc-gateway entry point https://github.com/mskalbania/workout-tracker/blob/main/grpc-gateway/main.go[grpc-gateway/main.go]
* grpc-gateway proto annotations https://github.com/mskalbania/workout-tracker/blob/main/proto/workout/v1/workout.proto[workout.proto]

== Setup

=== Local Stack

Docker compose file is provided to spin up services and dependencies.
Run below command to start services - https://github.com/mskalbania/workout-tracker/blob/main/docker-compose.yaml[docker-compose.yaml]

- grpc-gateway
- single postgres instance
- authorization server
- workout tracker server

After stack is ready, request collection can be used from here https://github.com/mskalbania/workout-tracker/blob/main/requests.http[requests.http].
It contains (JetBrains HTTP client) REST API collection to interact with application.

Alternatively, happy path E2E test can be found here https://github.com/mskalbania/workout-tracker/tree/main/e2e/e2e.http[e2e.http].

=== Tests

To run tests locally, below steps are required:

1. run `mockery --all --with-expecter` inside selected app directory _(authorization-server | workout-tracker-server)_ to generate mock files, this requires installing 3rd party tool mockery `brew install mockery`
2. run `protoc-all.sh` in root dir to generate all proto code

== More Ideas or TODO:

* Add API tests for workout API
* Implement scheduling and report generation requirement
* Add refresh tokens - currently re-login is required after access token expiry.
* Switch to always online validation of JWT tokens and keep offline as fallback to invalidate JWT tokens on logout, currently logout = remove token from device cache. Since project is gRPC latency tradeoff could be acceptable.