###REST Collection - goes through grpc-gateway
POST localhost:8080/v1/auth/register
Content-Type: application/json

{
  "username": "ghost",
  "password": "qwerty"
}
###
POST localhost:8080/v1/auth/login
Content-Type: application/json

{
  "username": "ghost",
  "password": "qwerty"
}
> {%
    client.global.set("token", response.body.token);
%}

###
GET localhost:8080/v1/exercises?muscle_group_filter=Back&category_filter=strength

###
POST localhost:8080/v1/workouts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Back Day",
  "owner": "4ff474ac-fb48-4bbc-8527-f7a3a44667c8",
  "exercises": [
    {
      "exercise_id": "94b4109b-25ba-4519-8aa7-6adef75c0d37",
      "order": 1,
      "repetitions": 10,
      "sets": 3
    }
  ]
}

###GRPC Collection (requires exposing ports in docker-compose)
GRPC localhost:8081/AuthorizationService/Register

{
  "username": "ghost",
  "password": "qwerty"
}
###
GRPC localhost:8081/AuthorizationService/Login

{
  "username": "ghost",
  "password": "qwerty"
}

> {%
    client.global.set("token", response.body.token);
%}
###
GRPC localhost:8082/ExerciseService/GetExercises

{
  "muscle_group_filter": "Back",
  "category_filter": "strength"
}
###
GRPC localhost:8082/WorkoutService/CreateWorkout
Authorization: Bearer {{token}}

{
  "name": "Back Day",
  "owner": "4ff474ac-fb48-4bbc-8527-f7a3a44667c8",
  "exercises": [
    {
      "exercise_id": "94b4109b-25ba-4519-8aa7-6adef75c0d37",
      "order": 1,
      "repetitions": 10,
      "sets": 3,
      "weight": 50
    }
  ]
}