###REST Collection - goes through grpc-gateway
POST localhost:8080/v1/auth/register
Content-Type: application/json

{
  "username": "ghost@gmail.com",
  "password": "qwerty-qwerty"
}

###
POST localhost:8080/v1/auth/login
Content-Type: application/json

{
  "username": "ghost@gmail.com",
  "password": "qwerty-qwerty"
}
> {%
    client.global.set("token", response.body.token);
%}

###
GET localhost:8080/v1/exercises?muscle_group_filter=Back&category_filter=strength

###
POST localhost:8080/v1/workouts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Back Day",
  "comment": "Do it as fast as you can",
  "exercises": [
    {
      "exercise_id": "94b4109b-25ba-4519-8aa7-6adef75c0d37",
      "order": 1,
      "repetitions": 10,
      "sets": 3,
      "weight": 50,
      "comment": "Do it slowly"
    }
  ]
}
> {%
    client.global.set("new_workout_id", response.body.id);
%}

###
GET localhost:8080/v1/workouts
Authorization: Bearer {{token}}

###
GET localhost:8080/v1/workouts/{{new_workout_id}}
Authorization: Bearer {{token}}

###
PATCH localhost:8080/v1/workouts/{{new_workout_id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Leg or Back Day",
  "comment": "Morning workout 22",
  "exercises": [
    {
      "exercise_id": "94b4109b-25ba-4519-8aa7-6adef75c0d37",
      "order": 2,
      "repetitions": 11,
      "sets": 5,
      "comment": "New exercise"
    },
    {
      "exercise_id": "94b4109b-25ba-4519-8aa7-6adef75c0d37",
      "order": 2,
      "repetitions": 11,
      "sets": 5,
      "comment": "Update existing"
    }
  ]
}

###
DELETE localhost:8080/v1/workouts/{{new_workout_id}}
Authorization: Bearer {{token}}

