###Register + Login E2E
< {%
    client.global.set("username", "test-" + $random.uuid)
    client.global.set("password", "password")
%}
POST http://localhost:8080/v1/auth/register
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.hasOwnProperty("userId"), "Cannot find 'userId' in response");
    });
%}

###
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.hasOwnProperty("token"), "Cannot find 'token' in response");
    });
%}