#GoLand inbuilt HTTP client request collection
GRPC localhost:8080/Authorization/Register

{
  "username": "ghost",
  "password": "qwerty"
}

###
GRPC localhost:8080/Authorization/Login

{
  "username": "ghost",
  "password": "qwerty"
}